apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: static-demo-pvc

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

  volumeName: static-demo-pv
  storageClassName: ""