apiVersion: v1
kind: Pod
metadata:
  name: static-demo-pod

spec:
  containers:
    - name: app
      image: nginx:alpine

      volumeMounts:
        - name: static-storage
          mountPath: /data

  volumes:
    - name: static-storage
      persistentVolumeClaim:
        claimName: static-demo-pvc