"""Add uploaded_questions table

Revision ID: bb3beb0f0ff7
Revises: 916a3c42ed8a
Create Date: 2026-07-11 19:39:13.394245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb3beb0f0ff7'
down_revision = '916a3c42ed8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('topic_slug', sa.String(length=100), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('option1', sa.Text(), nullable=False),
    sa.Column('option2', sa.Text(), nullable=False),
    sa.Column('option3', sa.Text(), nullable=False),
    sa.Column('option4', sa.Text(), nullable=False),
    sa.Column('correct_answer', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['upload_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uploaded_questions')
    # ### end Alembic commands ###
