"""Initial schema

Revision ID: d056ff078714
Revises: bb3beb0f0ff7
Create Date: 2026-07-22 00:27:51.091289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd056ff078714'
down_revision = 'bb3beb0f0ff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('wiki_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_answer', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=30), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('time_taken_seconds', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_attempts_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_player_name'), ['player_name'], unique=False)
        batch_op.create_index('ix_quiz_attempts_player_topic', ['player_name', 'topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempts_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index('ix_quiz_attempts_topic_score', ['topic_id', 'score'], unique=False)

    op.create_table('quiz_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('player_name', sa.String(length=30), nullable=False),
    sa.Column('question_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('submitted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_sessions_topic_id'), ['topic_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_sessions_topic_id'))

    op.drop_table('quiz_sessions')
    with op.batch_alter_table('quiz_attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_quiz_attempts_topic_score')
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_topic_id'))
        batch_op.drop_index('ix_quiz_attempts_player_topic')
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_player_name'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempts_completed_at'))

    op.drop_table('quiz_attempts')
    op.drop_table('questions')
    op.drop_table('wiki_pages')
    op.drop_table('topics')
    # ### end Alembic commands ###
