apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_LINK: cG9zdGdyZXNxbDovL3BnYWRtaW46Q2hhbmdlTWUxMjMhQHRpbnktcGcuYzZyc21rOGVnMTdrLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTo1NDMyL215ZGI=