# This workflow builds the dojo app and pushes the image to ECR
---
name: dojo-serverless-build-deploy

on:
  push:
    # Only trigger the workflow when there is a change in the app directory
    branches:
      - main
    paths:
      - "devops-dojo-serverless/app/frontend/**"
      - "devops-dojo-serverless/app/backend/**"

  # Manual trigger for the workflow
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        required: true
        options:
          - dev
          - prod

env:
  AWS_REGION: us-east-1
  # ECR_REPO: 023192525105.dkr.ecr.us-east-1.amazonaws.com/devopsdojo-dev-backend

jobs:
  build-and-push-image:
    # This job:
    # - Runs on a GitHub-hosted runner
    # - Builds the Docker image
    # - Authenticates to AWS ECR
    # - Pushes the image
    name: Build & Push - ${{ matrix.services.name }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }} # it means, needs an approval before we deploy the job. configured in gh>>settings>>enviornments

    strategy:
      matrix:
        services:
          - name: backend
            path: terraform-ecs-3tier-deployment/app/backend
            ecr_repo: 023192525105.dkr.ecr.us-east-1.amazonaws.com/devopsdojo-${{ inputs.environment }}-backend
          - name: frontend
            path: terraform-ecs-3tier-deployment/app/frontend
            ecr_repo: 023192525105.dkr.ecr.us-east-1.amazonaws.com/devopsdojo-${{ inputs.environment }}-frontend

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Authenticate Docker to ECR
      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push ${{ matrix.services.name }} image to ECR
        run: |
          cd ${{ matrix.services.path }}
          docker buildx build --platform linux/amd64 --push \
          -t ${{ matrix.services.ecr_repo }}:${{ github.sha }} \
          -t ${{ matrix.services.ecr_repo }}:latest .

  prepare-task-definition:
    name: Prepare Backend Task Definition
    needs: build-and-push-image
    runs-on: ubuntu-latest

    # Outputs exposes to use the attribute in another jobs same like terraform outputs
    outputs:
      task_definition_arn: ${{ steps.register.outputs.task_definition_arn }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download Backend Task Definition
        run: |
          aws ecs describe-task-definition \
            --task-definition dojo-${{ inputs.environment }}-backend \
            --query taskDefinition \
            > task-definition.json

      - name: Update Backend Image
        run: |
          jq '.containerDefinitions[0].image = "023192525105.dkr.ecr.us-east-1.amazonaws.com/devopsdojo-${{ inputs.environment }}-backend:${{ github.sha }}" |
              del(
                .taskDefinitionArn,
                .revision,
                .status,
                .requiresAttributes,
                .compatibilities,
                .registeredAt,
                .registeredBy
              )' \
            task-definition.json > task-definition-updated.json

      - name: Register New Task Definition
        id: register
        run: |
          TASK_DEF=$(aws ecs register-task-definition \
            --cli-input-json file://task-definition-updated.json \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)

          echo "task_definition_arn=$TASK_DEF" >> $GITHUB_OUTPUT

  migration:
    name: Database Migration
    needs: prepare-task-definition
    runs-on: ubuntu-latest
    env:
      ECS_CLUSTER: dojo-${{ inputs.environment }}-cluster
      CONTAINER_NAME: dojo-backend-container
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Run DB migration via ECS Task
        run: |
          # Get Backend Security Group ID
          ECS_SECURITY_GROUP=$(aws ec2 describe-security-groups \
            --filters "Name=group-name,Values=dojo-${{ inputs.environment }}-backend-sg" \
            --query "SecurityGroups[0].GroupId" \
            --output text)

          # Get Private Subnet ID
          ECS_SUBNET=$(aws ec2 describe-subnets \
            --filters "Name=tag:Name,Values=${{ inputs.environment }}-devopsdojo-private-1" \
            --query "Subnets[0].SubnetId" \
            --output text)

          echo "Backend SG: $ECS_SECURITY_GROUP"
          echo "Private Subnet: $ECS_SUBNET"

          TASK_ARN=$(aws ecs run-task \
            --cluster ${{ env.ECS_CLUSTER }} \
            --launch-type FARGATE \
            --task-definition ${{ needs.prepare-task-definition.outputs.task_definition_arn }} \
            --network-configuration "awsvpcConfiguration={subnets=[$ECS_SUBNET],securityGroups=[$ECS_SECURITY_GROUP],assignPublicIp=DISABLED}" \
            --overrides '{"containerOverrides":[{"name":"${{ env.CONTAINER_NAME }}","command":["/bin/sh","migrate.sh"]}]}' \
            --query 'tasks[0].taskArn' \
            --output text)

          echo "Migration task started: $TASK_ARN"

          aws ecs wait tasks-stopped \
            --cluster ${{ env.ECS_CLUSTER }} \
            --tasks "$TASK_ARN"

          EXIT_CODE=$(aws ecs describe-tasks \
            --cluster ${{ env.ECS_CLUSTER }} \
            --tasks "$TASK_ARN" \
            --query 'tasks[0].containers[0].exitCode' \
            --output text)

          STOP_REASON=$(aws ecs describe-tasks \
            --cluster ${{ env.ECS_CLUSTER }} \
            --tasks "$TASK_ARN" \
            --query 'tasks[0].stoppedReason' \
            --output text)

          if [ "$EXIT_CODE" != "0" ]; then
            echo "Migration failed with exit code $EXIT_CODE (reason: $STOP_REASON)"
            exit 1
          fi

          echo "Migration completed successfully"

  
  deploy-backend:
    name: Deploy Backend
    needs:
      - prepare-task-definition
      - migration
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy Backend
        shell: bash
        run: |
          echo "Deploying Task Definition:"
          echo "${{ needs.prepare-task-definition.outputs.task_definition_arn }}"

          aws ecs update-service \
            --cluster dojo-${{ inputs.environment }}-cluster \
            --service dojo-${{ inputs.environment }}-backend-service \
            --task-definition "${{ needs.prepare-task-definition.outputs.task_definition_arn }}"

          aws ecs wait services-stable \
            --cluster dojo-${{ inputs.environment }}-cluster \
            --services dojo-${{ inputs.environment }}-backend-service

          echo "Backend deployment completed successfully."

  deploy-frontend:
    name: Deploy Frontend
    needs: deploy-backend
    runs-on: ubuntu-latest

    env:
      ECS_CLUSTER: dojo-${{ inputs.environment }}-cluster
      ECS_TASK_DEF: dojo-${{ inputs.environment }}-frontend
      ECS_SERVICE: dojo-${{ inputs.environment }}-frontend-service
      ECR_REPO: 023192525105.dkr.ecr.us-east-1.amazonaws.com/devopsdojo-${{ inputs.environment }}-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Download Frontend Task Definition
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ env.ECS_TASK_DEF }} \
            --query taskDefinition \
            > task-definition.json

      - name: Update Frontend Image
        run: |
          jq '.containerDefinitions[0].image = "${{ env.ECR_REPO }}:${{ github.sha }}" |
              del(
                .taskDefinitionArn,
                .revision,
                .status,
                .requiresAttributes,
                .compatibilities,
                .registeredAt,
                .registeredBy
              )' \
            task-definition.json > task-definition-updated.json

      - name: Deploy Frontend
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: task-definition-updated.json
          service: ${{ env.ECS_SERVICE }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: false





  